import cors from 'cors';
import 'dotenv/config';
import express, { Express } from 'express';
import helmet from 'helmet';
import connectDB from './db/config';
import isAuthenticated from './middleware/isauthenticated';
import logger from './middleware/logger';
import urlRouter from './routes/url.route';
import userRouter from './routes/user.route';
const app: Express = express();
const port = process.env.PORT;
app.use(cors());
app.use(helmet());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
connectDB();
app.use(logger);

app.use('/user', userRouter);
app.use(isAuthenticated);
app.use('/url', urlRouter);
// app.post('/form', validateForm, formUrl);
app.listen(port, () => console.log(`Server Started at ${port}`));
