export default {
  expire: '1d',
  secret: crypto.randomUUID(),
};
export const STATUS_CODES = {
  // Informational responses (100–199)
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,

  // Successful responses (200–299)
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  // Redirection messages (300–399)
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  SWITCH_PROXY: 306, // No longer used
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // Client error responses (400–499)
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // Server error responses (500–599)
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,

  // Unofficial codes
  CHECKPOINT: 103, // Used in some applications
  THIS_IS_FINE: 218, // Used in some applications
  PAGE_EXPIRED: 419, // Used in some applications
  METHOD_FAILURE: 420, // Used in some applications
  ENHANCE_YOUR_CALM: 420, // Used by Twitter
  BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS: 450, // Used by Microsoft
  INVALID_TOKEN: 498, // Used by Esri
  TOKEN_REQUIRED: 499, // Used by Esri
  CLIENT_CLOSED_REQUEST: 499, // Used in some applications
  RETRY_WITH: 449, // Used by Microsoft
  REDIRECT: 451, // Used in some applications
  REQUEST_HEADER_TOO_LARGE: 494, // Used in some applications
  SSL_CERTIFICATE_ERROR: 495, // Used in some applications
  SSL_CERTIFICATE_REQUIRED: 496, // Used in some applications
  HTTP_REQUEST_SENT_TO_HTTPS_PORT: 497, // Used in some applications
  INVALID_SSL_CERTIFICATE: 526, // Used in some applications
  SITE_IS_OVERLOADED: 529, // Used in some applications
  SITE_IS_FROZEN: 530, // Used in some applications
  NETWORK_READ_TIMEOUT_ERROR: 598, // Used in some applications
  NETWORK_CONNECT_TIMEOUT_ERROR: 599, // Used in some applications
};
